### PR TITLE
Use double-type for weights and nodes

### PR DESCRIPTION
**Pull request by michael-hartmann**
Replace long doubles by doubles.

On x86 and x86-64 long doubles are - dependent on the compiler - usually 80bits (extended double). Due to aliasing one long double usually consumes 128 bits of space and the calculations can only be performed on the floating point unit (FPU). SSE or other extension cannot be used for long double calculations.
On most other architectures long doubles are identical to doubles.

CQUADPACK performs a numerical integration. The integrand returns its result as a double, so I don't think it is necessary or useful to use long doubles for weights and nodes.

### CODE REVIEW

**Comment by edisongustavo** [comment]
Thanks for the PR.

@tadeu Would you mind reviewing this patch too?

**Comment by edisongustavo** [comment]
I want to merge this and create another release.

**Comment by nicoddemus** [comment]
Should we create a conda-forge recipe as well?

**Comment by edisongustavo** [comment]
> Should we create a conda-forge recipe as well?

Yes.

**Comment by michael-hartmann** [comment]
It might be useful to check if there are further problems before creating a new release.

Actually, I was debugging quite a bit till I realized that the problem was not caused by my callback function. I used LLVM's C compiler clang to check if the code accesses uninitialized memory.

There also seems to be a another problem, so please be patient before creating another release. I'm on it. ;-)

**Comment by michael-hartmann** [comment]
I found one more issue, see the new PR.

**Comment by michael-hartmann** [comment]
What about this PR?

It doesn't make sense to use long doubles: Weights and nodes are in double format, because they do not have the suffix L. Even on platforms where long doubles are more accurate than doubles (e.g. x86 with gcc), the weights and nodes won't be more accurate.

On the other hand, long doubles cannot be processed with SSE or other extensions and take more space in memory. Due to aligning long doubles probably take up twice the amount of space than doubles.

**Comment by edisongustavo** [comment]
I was waiting for @tadeu to review, but tbh, I will just merge it since it looks ok to me.

Let's not stall PRs from people, it is bad for morale.

**Comment by michael-hartmann** [comment]
Thank you! :)

**Comment by tadeu** [comment]
@michael-hartmann Thanks for the other fixes too, sorry for the delay, I forgot @edisongustavo had mentioned me here.

**Pull request merged**
